<?php
/**
 * Title: Our Team
 * Slug: nextora/our-team
 * Categories: team
 * Description: Full-width nextora/team-section in the default style—light band with dark heading, intro, CTA, and a Swiper carousel of member portrait cards (name, role, tags)—for About or leadership pages.
 *
 * @package Nextora
 * @subpackage Patterns
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"right":"0","left":"0","top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:nextora/team-section {"members":[{"id":"1","photoId":0,"photoUrl":"https://pub-0645c3b9d3674132af6b362484df0f3c.r2.dev/alonepro/team-01.jpg","photoAlt":"","name":"James Carter","role":"Founder \u0026 CEO","tags":["Donations","Campaigns"],"bio":"Leads fundraising initiatives and partnerships that help provide resources for children and families in need.","bioLineClamp":3,"showSocialLinks":false,"socialLinks":[],"cardBorderRadius":16},{"id":"2","photoId":0,"photoUrl":"https://pub-0645c3b9d3674132af6b362484df0f3c.r2.dev/alonepro/team-02.jpg","photoAlt":"","name":"Sophia Nguyen","role":"Program Director","tags":["Community Care","Events"],"bio":"Coordinates impactful charity programs and community events that bring people together with purpose.","bioLineClamp":3,"showSocialLinks":false,"socialLinks":[],"cardBorderRadius":16},{"id":"3","photoId":0,"photoUrl":"https://pub-0645c3b9d3674132af6b362484df0f3c.r2.dev/alonepro/team-03.jpg","photoAlt":"","name":"Michael Rodrigue","role":"Operations Coordinator","tags":["Non-profit","Management"],"bio":"Ensures daily operations run smoothly while supporting volunteers, donors, and outreach activities.","bioLineClamp":3,"showSocialLinks":false,"socialLinks":[],"cardBorderRadius":16},{"id":"4","photoId":0,"photoUrl":"https://pub-0645c3b9d3674132af6b362484df0f3c.r2.dev/alonepro/team-04.jpg","photoAlt":"","name":"Emma Carter","role":"Outreach Coordinator","tags":["Education","Volunteer Support"],"bio":"Builds strong relationships with local families and organizes outreach programs that inspire positive change.","bioLineClamp":3,"showSocialLinks":false,"socialLinks":[],"cardBorderRadius":16}],"descriptionText":"People united to create positive change.","align":"full","className":"is-style-default","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}}} /--></div>
<!-- /wp:group -->