export type BoxIconLayoutMode = 'slider' | 'grid';
export type BoxIconIconSource = 'theme' | 'upload';
export type BoxIconIconStyle = 'default' | 'stacked' | 'framed';
export type BoxIconCardTemplate = 'default' | 'ways' | 'minimal' | 'highlights' | 'timeline';
export type BoxIconScrollAnimationStyle = 'default' | 'sequential';

export interface BoxIconItem {
	id: string;
	number: string;
	title: string;
	description: string;
	showLink: boolean;
	linkLabel: string;
	linkUrl: string;
	linkTarget: '_self' | '_blank';
	iconSource?: BoxIconIconSource;
	iconName: string;
	uploadedIconId: number;
	uploadedIconUrl: string;
	iconColor: string;
	iconSurfaceBackgroundColor: string;
	highlightAccentColor: string;
}

export interface BoxIconAttributes {
	items: BoxIconItem[];
	contentMaxWidth: string;
	cardTemplate: BoxIconCardTemplate;
	layoutMode: BoxIconLayoutMode;
	gridColumns: number;
	gridColumnsTablet: number;
	gridColumnsMobile: number;
	gridMinWidth: number;
	disableResponsiveCarousel: boolean;
	cardMinHeight: number;
	cardPadding: Record<string, string>;
	cardBorderWidth: number;
	cardBorderRadius: number;
	iconSource: BoxIconIconSource;
	iconSize: number;
	strokeWidth: number;
	iconCircleSize: number;
	iconCircleRadius: number;
	iconStyle: BoxIconIconStyle;
	iconColor: string;
	iconSurfaceBackgroundColor: string;
	iconSurfaceBorderColor: string;
	iconHoverColor: string;
	iconHoverSurfaceBackgroundColor: string;
	slidesPerView: number;
	slidesPerViewTablet: number;
	slidesPerViewMobile: number;
	spaceBetween: number;
	speed: number;
	loop: boolean;
	autoplay: boolean;
	autoplayDelay: number;
	pauseOnHover: boolean;
	showPagination: boolean;
	showArrows: boolean;
	grabCursor: boolean;
	freeMode: boolean;
	cardBorderColor: string;
	cardBackgroundColor: string;
	cardHoverBackgroundColor: string;
	cardTitleColor: string;
	cardDescriptionColor: string;
	descriptionHoverColor: string;
	linkColor: string;
	linkHoverColor: string;
	waysAccentColor1: string;
	waysAccentColor2: string;
	waysAccentColor3: string;
	paginationColor: string;
	paginationActiveColor: string;
	arrowColor: string;
	headingFontFamily: string;
	enableScrollAnimation: boolean;
	scrollAnimationStyle: BoxIconScrollAnimationStyle;
	enableCardHover: boolean;
	highlightAccentColor1: string;
	highlightAccentColor2: string;
	highlightAccentColor3: string;
	highlightAccentColor4: string;
	protocolTimelineColor: string;
	showTimelineLine: boolean;
	showTimelineTime: boolean;
	timelineAlign: 'left' | 'center' | 'right';
}
